### ISSUE TITLE
Why...

### ISSUE THREAD

**Issue by ghost** [Oren-Lindsey/wasteof-client#6]
...

**Comment by Oren-Lindsey** [comment]
![rickroll](https://user-images.githubusercontent.com/37572049/90699500-0cc3ec00-e2a1-11ea-8d13-989526e86b0e.gif)

**Comment by ghost** [comment]
... does it do that ...

**Comment by Oren-Lindsey** [comment]
https://github.com/marketplace/actions/random-rickroll
